import './globals.css'
import { Inter } from 'next/font/google'
import "./layout.css";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-1440 mx-auto`}>
      {children}
      </body>
    </html>
  )
}
